const arr = [
  {
    id: 0,
    name: " كعكة الفيريرو ",
    price: " 35 ₪ ",
    imageUrl:
      "https://e3arabi.com/wp-content/uploads/2021/04/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%B9%D9%85%D9%84-%D9%83%D9%8A%D9%83-%D9%81%D8%B1%D9%8A%D8%B1%D9%88-%D8%B1%D9%88%D8%B4%D9%8A%D9%87-768x512.jpg?ezimgfmt=ngcb1/notWebP",
    desc: " ... ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 1,
    name: " كعكة الاوريو ",
    price: " 35 ₪ ",
    imageUrl: "https://tullep.com/wp-content/uploads/2021/10/%D9%83%D9%8A%D9%83%D8%A9-%D8%A7%D9%84%D8%A3%D9%88%D8%B1%D9%8A%D9%88-1.jpg",
    desc: " كعكة الاوريو الشهية ، صنعنا الخاص ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 2,
    name: " كعكة الالفاخورس ",
    price: " 35 ₪ ",
    imageUrl: "https://i.ytimg.com/vi/pb4miUsIfmA/maxresdefault.jpg",
    desc: " ... ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 3,
    name: " كعكة الباونتي ",
    price: " 35 ₪ ",
    imageUrl: "https://www.mogazmasr.com/wp-content/uploads/2020/11/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%B9%D9%85%D9%84-%D9%83%D9%8A%D9%83%D8%A9-%D8%A7%D9%84%D8%A8%D8%A7%D9%88%D9%86%D8%AA%D9%8A-%D8%A8%D8%A8%D8%B9%D8%B6-%D8%A7%D9%84%D8%AE%D8%B7%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D8%A8%D8%B3%D9%8A%D8%B7%D8%A9.jpg",
    desc: " ... ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 4,
    name: " كعكة البيجلا والكراميل ",
    price: " 35 ₪ ",
    imageUrl: "https://i.ytimg.com/vi/tgyHfO7ShuQ/maxresdefault.jpg",
    desc: " ... ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 5,
    name: " سوفلي شوكولاتة ",
    price: " 35 ₪ ",
    imageUrl: "https://www.tareekaa.com/wp-content/uploads/2019/07/%D8%B3%D9%88%D9%81%D9%84%D9%8A%D9%87-%D8%A7%D9%84%D8%B4%D9%88%D9%83%D9%88%D9%84%D8%A7%D8%AA%D9%87.jpg",
    desc: " سوفلي شوكولاتة يقدم ساخن مع اضافة بوظة فانيل ",
    cat: "سبيشل لاتيه",
  },
  {
    id: 6,
    name: " وافل بلجي شخصي ",
    price: " 30 ₪ ",
    imageUrl: "https://yummy.awicdn.com/site-images/sites/default/files/prod/recipe/8/f/468038/7727a31fb71518f55e3ab482dcabb95805b2d41c-070422111906.jpg?preset=v3.0_1200xDYN&save-png=1&rnd=1519151RND220215",
    desc: " ... ",
    cat: "وافل بلجيكي",
  },
  {
    id: 7,
    name: " وافل بلجي عائلي ",
    price: " 50 ₪ ",
    imageUrl: "null",
    desc: " وافل بلجي باضافة شوكولاته ",
    cat: "وافل بلجيكي",
  },
  {
    id: 8,
    name: " فخفخينا فواكة ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "سموثي",
  },
  {
    id: 9,
    name: " تمر وموز سموثي ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي تمر ، موز ، حليب ، بوظة فانيل ",
    cat: "سموثي",
  },
  {
    id: 10,
    name: " موز الهند سموثي ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي الموز ، جوز الهند ، الحليب والأناناس ",
    cat: "سموثي",
  },
  {
    id: 11,
    name: " ميكس بيري سموثي ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي خليط فواكه برية ",
    cat: "سموثي",
  },
  {
    id: 12,
    name: " اناناس سموثي ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي اناناس ",
    cat: "سموثي",
  },
  {
    id: 13,
    name: " اناناس وبسفلورا سموثي ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي اناناس وبسفلورا ",
    cat: "سموثي",
  },
  {
    id: 14,
    name: " سموثي الافوكادو ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " سموثي الافوكادو باضافة القشطة ، سيلان ، وكاشيو ",
    cat: "سموثي",
  },
  {
    id: 15,
    name: " شوكوشيبس ",
    price: " 12 ₪ ",
    imageUrl: "null",
    desc: " شوكولاتة شيبس باضافة اسبريسو وحليب ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 16,
    name: " نسكافيه ",
    price: " 10 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 17,
    name: " هفوخ ",
    price: " 10 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 18,
    name: " شوكو ساخن ",
    price: " 10 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 19,
    name: " سحلب ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 20,
    name: " سحلب لوتوس ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 21,
    name: " اسبرسو قصير ",
    price: " 7 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 22,
    name: " اسبرسو دبل طويل ",
    price: " 9 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 23,
    name: " اسبرسو دبل قصير ",
    price: " 9 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 24,
    name: " مشروب الصحة ",
    price: " 12 ₪ ",
    imageUrl: "null",
    desc: " زنجبيل ، نعنع ، عسل ، قرفة ، برتقال ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 25,
    name: " شوكو بومب ",
    price: " 12 ₪ ",
    imageUrl: "null",
    desc: " شوكو وشوكولاته ، باضافة مرشميلو ",
    cat: "مشروبات ساخنة",
  },
  {
    id: 26,
    name: " ميلكشيك فانيل ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 27,
    name: " ميلك شيك اوريو ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 28,
    name: " ميلك شيك لوتوس ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 29,
    name: " ميلك شيك بازوكا ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 30,
    name: " ملك شيك السنافر ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 31,
    name: " ملكشيك بيجلا وكراميل ",
    price: " 23 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "ميلك شيك",
  },
  {
    id: 32,
    name: " كريب لاتيه بالشوكولاتة ",
    price: " 40 ₪ ",
    imageUrl: "null",
    desc: " كريب فرنسي عائلي باضافة شوكولاتة وبوظة ",
    cat: "كريب فرنسي",
  },
  {
    id: 33,
    name: " كريب لاتيه بالفستق الحلبي والشوكلاتة ",
    price: " 45 ₪ ",
    imageUrl: "null",
    desc: " كريب فرنسي عائلي باضافة فستق حلبي وشوكلاتة وبوظة ",
    cat: "كريب فرنسي",
  },
  {
    id: 34,
    name: " كريب فرنسي شخصي ",
    price: " 20 ₪ ",
    imageUrl: "null",
    desc: " كريب فرنسي شخصي باضافة شوكولاته ",
    cat: "كريب فرنسي",
  },
  {
    id: 35,
    name: " فشافيش شخصي ",
    price: " 30 ₪ ",
    imageUrl: "null",
    desc: " 15 حبة فشافيش مقدم مع شوكولاتة ",
    cat: "فشافيش",
  },
  {
    id: 36,
    name: " فشافيش عائلي ",
    price: " 50 ₪ ",
    imageUrl: "null",
    desc: " 25 حبة فشافيش باضافة شوكولاتة ",
    cat: "فشافيش",
  },
  {
    id: 37,
    name: " جروس ليمون نعنع ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات باردة",
  },
  {
    id: 38,
    name: " ماء صغير ",
    price: " 5 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات باردة",
  },
  {
    id: 39,
    name: " ايس كوفي ",
    price: " 18 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات باردة",
  },
  {
    id: 40,
    name: " سبانيش لاتيه ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "مشروبات باردة",
  },
  {
    id: 41,
    name: " موهيتو ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "موهيتو",
  },
  {
    id: 42,
    name: " موهيتو توت ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "موهيتو",
  },
  {
    id: 43,
    name: " موهيتو بطيخ ",
    price: " 15 ₪ ",
    imageUrl: "null",
    desc: " ... ",
    cat: "موهيتو",
  },
];
export default arr;
